### PR TITLE
[feature] Add tetrio command

### PR DESCRIPTION
**Pull request by sourTaste000**
@zeroeightysix

### CODE REVIEW

**Comment by sourTaste000** [comment]
Preview:
Screen Shot 2021-03-08 at 11 34 15 AM

**Comment by humboldt123** [comment]
Please change the inconsistent naming scheme in the dataclasses.

**Comment by humboldt123** [comment]
Also please convert Games Played/Won to a human readable format

**Review by humboldt123 — COMMENTED** [review]
Please convert Games Played/Won to a human readable format

**Comment by humboldt123** [comment]
Thanks!

**Pull request merged**
